### PR TITLE
Bump to v2.0.0

### LINKED ISSUE #2: Update to version v2.0.0
Versions v1.4.13 and v1.4.14 also came out since the last commit.

I'll see if I can make a PR for v2.0.0.

### PR DESCRIPTION
**Pull request by WaveHack**
Works like a charm out of the box.

The license you provided might be broken with the update. I suggest removing it, also to prevent the package being potentially removed from the AUR.

Fixes #2

### CODE REVIEW

**Comment by WaveHack** [comment]
If you do remove the license crack, feel free to add me as collaborator on GitHub and/or AUR if you want.

**Comment by KillWolfVlad** [comment]
Thanks, I'll deal with this in a few hours.

**Comment by KillWolfVlad** [comment]
@WaveHack what is your [qt5-base](https://www.archlinux.org/packages/extra/x86_64/qt5-base/) package version?

I have `[1]    3588 segmentation fault (core dumped)  gitahead` on v5.10.0-1, but on v5.9.3-1 or build-in qt all fine

**Comment by WaveHack** [comment]
5.9.3-1. And I see a system update pending for this package. I'll update my box this weekend and take a look into it.

If you managed to find anything in the meantime, please let me know.

**Comment by KillWolfVlad** [comment]
GitAhead should be recompiled with new Qt version. I will change `PKGBUILD` to use build-in qt.

**Comment by KillWolfVlad** [comment]
@WaveHack can you test `PKGBUILD` from [develop-new-version](https://github.com/KillWolfVlad/GitAhead-AUR/tree/develop-new-version) branch?

**Comment by WaveHack** [comment]
Will try

**Comment by WaveHack** [comment]
Works like a charm!

**Comment by KillWolfVlad** [comment]
Merged as part of e2a00961a1e9b639b3a9340d399974825ede2270

> add me as collaborator/maintainer on GitHub and/or AUR for this package

Maybe in the future. But you can send PRs

> I suggest removing it

I remove `infinity` branch. Now I use Non-Commercial License

**Pull request closed without merging**
